import { chromium } from "playwright";
import fs from "fs";
const [, , donnees, sortie, personne] = process.argv;
const js = fs.readFileSync(new URL("../www/vision-maison-card.js", import.meta.url), "utf8");
const maison = fs.readFileSync(donnees, "utf8");
const nav = await chromium.launch();
const page = await nav.newPage({ viewport: { width: 900, height: 1400 } });
await page.setContent(`<html><body style="background:#fafafa;font-family:sans-serif;--divider-color:#ddd;--primary-color:#8C2F4B;--secondary-text-color:#666;--card-background-color:#fff;--secondary-background-color:#f1f1f1"><div id="z" style="max-width:820px"></div></body></html>`);
await page.addScriptTag({ content: `customElements.define("ha-card", class extends HTMLElement {}); customElements.define("ha-icon", class extends HTMLElement {});` + js });
const erreurs = []; page.on("pageerror", (e) => erreurs.push(String(e)));
await page.evaluate(([m, personne]) => {
  window.gestes = [];
  const c = document.createElement("vision-maison-card");
  c.setConfig({ mode: "personne", personne: personne, chemin: "/vision-maison" });
  c.hass = { callApi: async (methode, chemin, corps) => { if (corps) window.gestes.push(corps); return JSON.parse(m); } };
  document.getElementById("z").appendChild(c); window.c = c;
}, [maison, personne || ""]);
await page.waitForTimeout(300);
const ok = (cond, quoi) => { console.log((cond ? "ok   " : "RATE ") + quoi); if (!cond) process.exitCode = 1; };
const r = () => page.locator("vision-maison-card");
ok(await r().locator(".limite").count() >= 1, "la section des limites s'affiche");
ok((await r().locator(".limite.atteinte .sous").first().innerText()).includes("Fermé jusqu"), "limite atteinte signalée");
await r().locator("h3", { hasText: "Temps par appli" }).scrollIntoViewIfNeeded();
await page.screenshot({ path: sortie + "/limites.png", fullPage: true });
await r().locator("[data-lim-retirer]").first().click(); await page.waitForTimeout(150);
let g = await page.evaluate(() => window.gestes.splice(0));
ok(g.length === 1 && g[0].action === "limite" && g[0].minutes === 0 && !!g[0].pc && !!g[0].nom, "retirer : " + JSON.stringify(g[0]));
await r().locator("[data-lim-min]").first().fill("90"); await r().locator("[data-lim-min]").first().dispatchEvent("change"); await page.waitForTimeout(150);
g = await page.evaluate(() => window.gestes.splice(0));
ok(g.length === 1 && g[0].minutes === 90 && !!g[0].pc, "changer la durée : " + JSON.stringify(g[0]));
const n = await r().locator("[data-lim-ajout]").count();
if (n) {
  await r().locator("[data-lim-neuf]").fill("30"); await r().locator("[data-lim-ajout] button").click(); await page.waitForTimeout(150);
  g = await page.evaluate(() => window.gestes.splice(0));
  ok(g.length === 1 && g[0].action === "limite" && g[0].minutes === 30 && !!g[0].nom, "ajouter : " + JSON.stringify(g[0]));
} else console.log("     (aucune autre appli à limiter dans ces données)");
ok(erreurs.length === 0, "aucune erreur de script " + erreurs.join(" | "));
await nav.close();
